{{- if and .Values.matrix.enabled (empty .Values.matrix.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hugo-webhook.fullname" . }}-matrix
  labels:
    {{- include "hugo-webhook.labels" . | nindent 4 }}
type: Opaque
data:
  room: {{ .Values.matrix.room | b64enc | quote }}
  token: {{ .Values.matrix.token | b64enc | quote }}
{{- end }}
