{{- if and (not (empty .Values.git.sshPrivateKey)) (not .Values.git.existingSshPrivateKeySecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: webhook-ssh-auth
type: kubernetes.io/ssh-auth
data:
  ssh-privatekey: {{ .Values.git.sshPrivateKey | b64enc | quote }}
{{- end }}