{{- if (not (empty .Values.git.gitCredentials))  }}
apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
type: Opaque
data:
  git-credentials: {{ .Values.git.gitCredentials | b64enc | quote }}
{{- end }}