{{- if and (not (empty .Values.git.webToken)) (not .Values.git.existingWebTokenSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: webhook-token
type: Opaque
data:
  token: {{ .Values.git.webToken | b64enc | quote }}
  username: {{ .Values.git.webUsername | b64enc | quote }}
{{- end }}